title: Zetark Statut
buildFuture: true
defaultContentLanguage: fr
languageCode: fr
baseURL: https://statut.zetark.fr
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: true
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Cap Fibre
      category: Fibre
    - name: Covage
      category: Fibre
    - name: "Hébergement Dédié "
      category: Services WEB
    - name: Hébergement Mutualisé
      category: Services WEB
    - name: 4G
      description: ""
      category: Telephonie
    - name: Trunk
      category: Telephonie
    - name: Centrex
      category: Telephonie
      description: ""
    - category: Telephonie
      name: Mobile
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/brut.png
  incidentPostsPerPage: 8
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: false
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Fibre
    - name: Telephonie
    - name: Services WEB
  description: >-
    ZETARK 

    Le tout numérique à portée de main

    Ce sont des solutions accessibles à toutes les entreprises, de toutes tailles, de tout âge et tout budget.


    Nous souhaitons vous apporter le meilleur de la technologie et de la sécurité informatique.


    Et ainsi vous aider à vous consacrer sereinement à votre cœur de métier.
  enableCustomHTML: true
  useLargeHeaderDesign: true
