title: Zetark Statut
buildFuture: true
defaultContentLanguage: fr
languageCode: fr
baseURL: https://statut.zetark.fr
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Gateway
      category: North Coast
    - name: Backup Gateway
      category: North Coast
    - name: Website
      description: The web frontend for the application.
      category: Uncategorized
      link: https://example.com/
    - name: API
      description: The guts of the application.
      category: Uncategorized
    - name: Media Proxy
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/brut.png
  incidentPostsPerPage: 8
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: North Coast
      description: The main servers are located here.
      closed: true
    - name: Empty Category
    - name: Uncategorized
      untitled: true
  description: >-
    ZETARK 

    Le tout numérique à portée de main

    Ce sont des solutions accessibles à toutes les entreprises, de toutes tailles, de tout âge et tout budget.


    Nous souhaitons vous apporter le meilleur de la technologie et de la sécurité informatique.


    Et ainsi vous aider à vous consacrer sereinement à votre cœur de métier.
  enableCustomHTML: false
  useLargeHeaderDesign: false
